### ISSUE TITLE
Update build process

### ISSUE THREAD

**Issue by Mark1626** [Mark1626/home-blocks#25]
**Is your feature request related to a problem? Please describe.**
Improve the build system for the project

**Describe the solution you'd like**
- Refractor the build step
- Might migrate to Gulp

Related to #24

**Comment by karuppiah7890** [comment]
I have not seen the code, or how the build is happening in detail. At a high level overview, it looks like grunt and webpack are being used. And I haven't really tried them

Other than fixing the issue with the build when there's a bug, and refactoring...
Might I suggest trying out parcel bundler instead of webpack? https://parceljs.org

Pro: I think parcel is very simple to use with zero configuration

Why not webpack - I have never tried to understand webpack because it looked so complex 🙈 . parcel was just `parcel index.html` for development and everything worked including hot reloading! And then `parcel build <entry-js-file>` to build (bundle things) and then you can use the bundled js.

I could create a PR for the same to show that it will make the build process simpler. What are your thoughts?

**Comment by Mark1626** [comment]
@karuppiah7890 Webpack is currently not an issue

The approach I have here is that I zip the webpack output, which will then be used to distribute the plugin. I was also new to grunt so the zip part alone was done in shell. Moving that to grunt will solve the issue.

Since gulp was trending thought I'll migrate to it

**Comment by karuppiah7890** [comment]
@M4rk9696 okay. So the issue is - when webpack build fails `yarn build` should fail but it doesn't. Right? And also creates a zip
